name: Update RSS Feed on New Video Upload

on:
  push:
    paths:
      - 'videos/*.json'

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate RSS feed
        run: |
          echo '<?xml version="1.0" encoding="UTF-8" ?>' > feed.xml
          echo '<rss version="2.0"><channel>' >> feed.xml
          echo '<title>Build with GenAI - Video Feed</title>' >> feed.xml
          echo '<link>https://github.com/victordelrosal/buildwithGenAI</link>' >> feed.xml
          echo '<description>Latest video updates</description>' >> feed.xml

          for file in videos/*.json; do
            id=$(jq -r '.id // empty' "$file")
            title=$(jq -r '.title // "Untitled Video"' "$file")
            description=$(jq -r '.description // "No description available."' "$file")
            thumbnail=$(jq -r '.thumbnail // empty' "$file")
            pubDate=$(jq -r '.date // "2025-02-06T00:00:00Z"' "$file")

            # Construct YouTube link if ID exists
            if [[ -n "$id" ]]; then
              link="https://www.youtube.com/watch?v=$id"
            else
              link="https://github.com/victordelrosal/buildwithGenAI"
            fi

            echo "<item>" >> feed.xml
            echo "<title>$title</title>" >> feed.xml
            echo "<link>$link</link>" >> feed.xml
            echo "<description><![CDATA[$description]]></description>" >> feed.xml
            echo "<pubDate>$pubDate</pubDate>" >> feed.xml

            # Add thumbnail if available
            if [[ -n "$thumbnail" ]]; then
              echo "<media:thumbnail url=\"$thumbnail\" />" >> feed.xml
            fi

            echo "</item>" >> feed.xml
          done

          echo '</channel></rss>' >> feed.xml

      - name: Commit and Push RSS Feed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add feed.xml
          git commit -m "Auto-update RSS feed with new video"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
