name: Update RSS Feed on New Video Upload

on:
  push:
    paths:
      - "videos/*.json"

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Disable default GitHub Actions auth

      - name: Generate RSS Feed
        run: echo '<?xml version="1.0" encoding="UTF-8" ?>' > feed.xml

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          git add feed.xml
          git commit -m "Auto-update RSS feed with new video"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/victordelrosal/buildwithGenAI.git main
