name: Update RSS Feed on New Video Upload

on:
  push:
    paths:
      - 'videos/*.json'

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate RSS Feed
        run: |
          echo '<?xml version="1.0" encoding="UTF-8" ?>' > feed.xml
          echo '<rss version="2.0"><channel>' >> feed.xml
          echo '<title>Build with GenAI - New Videos</title>' >> feed.xml
          echo '<link>https://victordelrosal.github.io/buildwithGenAI/</link>' >> feed.xml
          echo '<description>A curated collection of videos about building with Generative AI</description>' >> feed.xml
          
          for file in videos/*.json; do
            title=$(jq -r '.title' "$file")
            description=$(jq -r '.description' "$file")
            video_id=$(jq -r '.id' "$file")
            pub_date=$(date -u +"%a, %d %b %Y %H:%M:%S GMT")
            
            echo "<item>" >> feed.xml
            echo "<title>$title</title>" >> feed.xml
            echo "<link>https://victordelrosal.github.io/buildwithGenAI/?video=$video_id</link>" >> feed.xml
            echo "<description>$description</description>" >> feed.xml
            echo "<pubDate>$pub_date</pubDate>" >> feed.xml
            echo "</item>" >> feed.xml
          done

          echo '</channel></rss>' >> feed.xml

      - name: Commit and Push RSS Feed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add feed.xml
          git commit -m "Auto-update RSS feed with new video"
          git push
